# Generated by Django 4.2 on 2023-04-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direccionResidencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion de residencia'),
        ),
        migrations.AddField(
            model_name='user',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Nacionalidad'),
        ),
        migrations.AddField(
            model_name='user',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=68, null=True, verbose_name='Sexo'),
        ),
    ]
