# Generated by Django 4.1.7 on 2023-04-17 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoresp',
            name='user_doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'doctor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctores_especilistas', to=settings.AUTH_USER_MODEL, verbose_name='Doctor'),
        ),
        migrations.CreateModel(
            name='cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField(null=True)),
                ('user_cliente', models.ForeignKey(limit_choices_to={'tipo': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='citas_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('user_doctor', models.ForeignKey(limit_choices_to={'tipo': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='citas_doctor', to=settings.AUTH_USER_MODEL, verbose_name='Doctor')),
            ],
        ),
    ]
