# Generated by Django 4.1.7 on 2023-04-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_cc_user_phone_alter_user_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.PositiveIntegerField(blank=True, help_text='+ 57', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
