# Generated by Django 4.1.7 on 2023-04-17 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_doctoresp_user_doctor_cita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoresp',
            name='user_doctor',
        ),
        migrations.DeleteModel(
            name='cita',
        ),
        migrations.DeleteModel(
            name='DoctorEsp',
        ),
    ]
