# Generated by Django 4.2 on 2023-04-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_direccionresidencia_user_nacionalidad_user_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nacionalidad',
        ),
        migrations.AlterField(
            model_name='user',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=68, null=True, verbose_name='Genero'),
        ),
    ]
