# Generated by Django 4.1.7 on 2023-04-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_phone_user_fechanacimiento_user_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cc',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero de documento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fechaNacimiento',
            field=models.DateField(blank=True, help_text='AAAA-MM-DD', null=True, verbose_name='Fecha nacimiento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('enfermero', 'Enfermero'), ('cliente', 'Cliente')], max_length=58, null=True, verbose_name='Tipo de usuario'),
        ),
    ]
