# Generated by Django 4.2 on 2023-05-01 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('enfermedades_previas', models.TextField(blank=True, null=True, verbose_name='Enfermedades')),
                ('medicamentos', models.TextField(blank=True, null=True, verbose_name='Medicamentos')),
                ('alergias', models.TextField(blank=True, null=True, verbose_name='Alergias')),
                ('examenes_realizados', models.TextField(blank=True, null=True, verbose_name='Examenes realizados')),
                ('user_clinte', models.ForeignKey(limit_choices_to={'tipo': 'cliente'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('user_doctor', models.ForeignKey(limit_choices_to={'tipo': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='historial_doctor', to=settings.AUTH_USER_MODEL, verbose_name='Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorEsp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espcialidad', models.CharField(blank=True, choices=[('anestesiologo', 'Anestesiólogo'), ('cardiologo', 'Cardiólogo'), ('cirujano', 'Cirujano'), ('dermatologo', 'Dermatólogo'), ('endocrinologo', 'Endocrinólogo'), ('gastroenterologo', 'Gastroenterólogo'), ('ginecologo', 'Ginecólogo'), ('hematologo', 'Hematólogo'), ('infectologo', 'Infectólogo'), ('internista', 'Internista'), ('nefrologo', 'Nefrólogo'), ('neurologo', 'Neurólogo'), ('oftalmologo', 'Oftalmólogo'), ('oncologo', 'Oncólogo'), ('otorrinolaringologo', 'Otorrinolaringólogo'), ('patologo', 'Patólogo'), ('pediatra', 'Pediatra'), ('psiquiatra', 'Psiquiatra'), ('radiologo', 'Radiólogo'), ('reumatologo', 'Reumatólogo'), ('traumatologo', 'Traumatólogo'), ('general', 'Médico General')], max_length=68, null=True, verbose_name='Especialidad')),
                ('user_doctor', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'doctor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctores_especilistas', to=settings.AUTH_USER_MODEL, verbose_name='Doctor')),
            ],
            options={
                'verbose_name': 'Dr. con especialidad',
                'verbose_name_plural': 'Dr. con especialidades',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora_I', models.DateTimeField(null=True, verbose_name='Fecha y hora de inicio')),
                ('fechaHora_F', models.DateTimeField(null=True, verbose_name='Fecha y hora de cierre')),
                ('user_cliente', models.ForeignKey(limit_choices_to={'tipo': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='citas_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('user_doctor', models.ForeignKey(limit_choices_to={'tipo': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='citas_doctor', to=settings.AUTH_USER_MODEL, verbose_name='Doctor')),
            ],
        ),
    ]
