# Generated by Django 4.1.7 on 2023-04-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_internos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='fechaHora',
        ),
        migrations.AddField(
            model_name='cita',
            name='fechaHora_F',
            field=models.DateTimeField(null=True, verbose_name='Fecha y hora de inicio'),
        ),
        migrations.AddField(
            model_name='cita',
            name='fechaHora_I',
            field=models.DateTimeField(null=True, verbose_name='Fecha y hora de inicio'),
        ),
    ]
