# Generated by Django 4.2 on 2023-04-24 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medios_internos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=68, null=True, verbose_name='Sexo')),
                ('direccionResidencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion de residencia')),
                ('nacionalidad', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nacionalidad')),
                ('user_cliente', models.ForeignKey(limit_choices_to={'tipo': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='info_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
        ),
    ]
