# Generated by Django 4.1.7 on 2023-04-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_internos', '0002_remove_cita_fechahora_cita_fechahora_f_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fechaHora_F',
            field=models.DateTimeField(null=True, verbose_name='Fecha y hora de cierre'),
        ),
    ]
